spring:
  application:
    name: JMonkey2.0
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  cache:
    type: redis
    redis:
      time-to-live: 86400000 #缓存超时时间ms 1天
      cache-null-values: false #是否缓存空值
  rabbitmq:
    host: ${jmonkey.rabbitmq.host}
    port: ${jmonkey.rabbitmq.port}
    username: ${jmonkey.rabbitmq.username}
    password: ${jmonkey.rabbitmq.password}
  redis:
    host: ${jmonkey.redis.host}
    port: ${jmonkey.redis.port}
    database: ${jmonkey.redis.database}
    timeout: 10000  #redis 连接超时时间ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${jmonkey.datasource.username}
      password: ${jmonkey.datasource.password}
      url: ${jmonkey.datasource.url}
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: select 1 from dual
      validationQueryTimeout: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,log4j2
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        slf4j:
          enabled: true
          connection-log-enabled: true
          connection-close-after-log-enabled: true
          connection-commit-after-log-enabled: true
          connection-connect-after-log-enabled: true
          connection-connect-before-log-enabled: true
          connection-log-error-enabled: true
          data-source-log-enabled: true
          result-set-log-enabled: true
          statement-log-enabled: true
        wall:
          enabled: true
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            #是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL
            none-base-statement-allow: false
            #检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
            update-where-none-check: true
            #SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
            select-into-outfile-allow: false
            #是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
            metadata-allow: true
            #允许多条sql一起执行
            multiStatementAllow: true
          #对被认为是攻击的SQL进行LOG.error输出
          log-violation: true
          #对被认为是攻击的SQL抛出SQLExcepton
          throw-exception: true
          db-type: mysql
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
          #你可以配置principalSessionName，使得druid能够知道当前的cookie的用户是谁
          #principal-cookie-name: admin
          #你可以配置principalSessionName，使得druid能够知道当前的session的用户是谁
          #principal-session-name: admin
          #设置profileEnable能够监控单个url调用的sql列表。
          profile-enable: true
          #session统计功能
          session-stat-enable: false
          #最大session数
          session-stat-max-count: 100000
        stat-view-servlet:
          #allow: ${GATEWAY_HOST:172.26.114.241}
          enabled: true
          login-username: admin
          login-password: 123456
          url-pattern: /druid/*
          #允许清除记录
          reset-enable: false
        aop-patterns: com.wang.jmonkey.modules.*.service.*
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: true
      exclude: templates/**,static/**,
  resources:
    static-locations: file:${jmonkey.static-locations-file},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


server:
  servlet:
    context-path: /
    session:
      tracking-modes: cookie

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.wang.jmonkey.modules.*.model.entity #实体扫描，多个package用逗号或者分号分隔
  global-config:
    id-type: 3 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 1 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-column-underline: true #驼峰下划线转换
    refresh-mapper: true #刷新mapper 调试神器
    #capital-mode: true #数据库大写下划线转换
    #key-generator: com.baomidou.springboot.xxx #序列接口实现类配置
    logic-delete-value: concat('','Delete','')  #逻辑删除配置
    logic-not-delete-value: concat('','Used','')
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #自定义SQL注入器
    metaObjectHandler: com.wang.jmonkey.common.mybatis.handler.DataMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  config: classpath:logback.xml
  level:
    com:
      wang: debug

jmonkey:
  baseUrl:
  auth:
    clientId: JMonkey_client_id
    clientSecret: JMonkey_client_secret
    scope: server
  token:
    expiresIn: 3600 # token过期时间，默认10小时，单位秒，60 * 60（一小时）
  urls:
    anon:
    - /auth/**
    - /signin
    - /signup
    - /favicon.ico
    - /page/**
    resources:
    - /css/**
    - /images/**
    - /lib/**
    - /scripts/**
    - /file/**