jmonkey:
  log:
    save: false #是否存储日志
    debug: false #是否打印访问接口日志
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    database: 10
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/j_monkey?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
  static-locations-path: http://49.4.54.245:8080/assets/
  static-locations-file: D:/JMonkeyFile
  filePath: /assets
  fileTempMemory: D:/fileTempMemory
  thymeleaf:
    staticPath: http://49.4.54.245:8080/lib/ #https://cdn.bootcss.com/
  page-office:
    lic-path:  D:/JMonkeyFile/assets/pageOffice/lic/
  user:
    photo: ${jmonkey.filePath}/user/photo/
  message:
    image: ${jmonkey.filePath}/message/image/
    file: ${jmonkey.filePath}/message/file/
    chat:
      im:
        file: ${jmonkey.filePath}/message/chat/im/
      group:
        image: ${jmonkey.filePath}/message/chat/image/
      history:
        clear: -7 #自动删除7天前的聊天记录
        backups: true #删除的聊天记录是否保存到Excel文件中
