jmonkey:
  static-locations-file: D:/JMonkeyFile
  fileTempMemory: D:/fileTempMemory
  thymeleaf:
    staticPath: http://49.4.54.245:8080/lib/ #https://cdn.bootcss.com/
  user:
    photo: /user/photo/